CREATE PROCEDURE AddProduct(@TITLE VARCHAR(300), @PRICE INT, @DESCRIPTION VARCHAR(1000), @CATEGORY VARCHAR(200), @IMAGE VARCHAR(1000) , @QUANTITY INT)
AS
BEGIN
	IF EXISTS( SELECT * FROM dbo.PRODUCTS WHERE TITLE=@TITLE)
	BEGIN
		RAISERROR('Item already exists',11,1);
		RETURN;
	END
	IF (@TITLE='' OR @PRICE='' OR @DESCRIPTION='' OR @CATEGORY= '' OR @IMAGE = '' OR @QUANTITY='')
	BEGIN
		RAISERROR('All fields are required',11,1);
		RETURN;
	END

	ELSE

	BEGIN
		INSERT INTO PRODUCTS (TITLE, PRICE, DESCRIPTION, CATEGORY, IMAGE, QUANTITY)
		VALUES(@TITLE, @PRICE, @DESCRIPTION, @CATEGORY, @IMAGE, @QUANTITY)
	END

END