DROP PROCEDURE deleteProduct
CREATE PROCEDURE deleteProduct (@ID INT)
AS 
BEGIN
	IF EXISTS( SELECT ID FROM dbo.PRODUCTS WHERE ID=@ID)
	BEGIN
		DELETE FROM dbo.PRODUCTS WHERE ID=@ID
	END
	ELSE
	BEGIN
		RAISERROR ('No Product With That ID',11,1);
		RETURN
	END
END